algoritmo "ResultadosTabuada"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujo
// Data atual  : 12/09/2025
var

    contadora, soma : inteiro

inicio

    contadora <- 1
    enquanto contadora < 101 faca
        soma <- contadora + soma
        contadora <- contadora + 1
    fimenquanto
    escreval (soma)

fimalgoritmo