algoritmo "SomatorioPar"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Matheus Nascimento de Araujo
// Data atual  : 17/09/2025
var

    contadora, contadora1: inteiro

inicio

    para contadora de 59 ate 1 passo -1 faca
        para contadora1 de 59 ate 1 passo -1 faca
             escreval(contadora," : ",contadora1)
        fimpara
    fimpara

fimalgoritmo